### ISSUE TITLE
Test suite fails since 2015-01-25

### ISSUE THREAD

**Issue by eserte** [gfx/mousex-getopt#5]
See http://matrix.cpantesters.org/?dist=mousex-getopt;reports=1#sl=7,1 for datetime-sorted list of pass/fail reports.

**Comment by pghmcfc** [comment]
This is caused by update of Getopt::Long::Descriptive to 0.099.

See https://github.com/gfx/mousex-getopt/pull/6

**Comment by hartzell** [comment]
See [this bug](https://rt.cpan.org/Ticket/Display.html?id=103161) and the [associated gist](https://gist.github.com/hartzell/dc5e258b27d7c976f194) for a patch that addresses this problem.

**Comment by gfx** [comment]
Fixed by #6 and released 0.36. Thanks.
